services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: catalogo_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - microservices-network

  eureka-server:
    image: cleosilva/eureka-server:latest
    build: ./service-discovery
    ports:
      - "8761:8761"
    networks:
      - microservices-network
    environment:
      TZ: America/Sao_Paulo

  product-catalog:
    image: cleosilva/product-catalog:latest
    ports:
      - "8100:8100"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/catalogo_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_APPLICATION_NAME: products-catalog
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      TZ: America/Sao_Paulo
    depends_on:
      - eureka-server
      - postgres
    networks:
      - microservices-network

  order-simulator:
    image: cleosilva/order-simulator:latest
    build: ./order-simulator
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: order-simulator
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      TZ: America/Sao_Paulo
    depends_on:
      - eureka-server
      - product-catalog
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  pgdata:
