services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: catalogo_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - microservices-network

  eureka-server:
    image: cleosilva/eureka-server:latest
    build: ./service-discovery
    ports:
      - "8761:8761"
    networks:
      - microservices-network
    environment:
      TZ: America/Sao_Paulo

  product-catalog:
    image: cleosilva/product-catalog:latest
    ports:
      - "8100:8100"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/catalogo_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_APPLICATION_NAME: products-catalog
      #EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      TZ: America/Sao_Paulo
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      - eureka-server
      - postgres
      - rabbitmq
    networks:
      - microservices-network

  order-simulator:
    image: cleosilva/order-simulator:latest
    build: ./order-simulator
    ports:
      - "8200:8200"
    environment:
      SPRING_APPLICATION_NAME: order-simulator
      #EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      TZ: America/Sao_Paulo
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      - eureka-server
      - product-catalog
      - rabbitmq
    networks:
      - microservices-network

  api-gateway:
    image: cleosilva/api-gateway:latest
    build: ./api-gateway
    ports:
      - "8700:8700"
    environment:
      SPRING_APPLICATION_NAME: api-gateway
      #EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      TZ: America/Sao_Paulo
    depends_on:
      - eureka-server
      - product-catalog
      - order-simulator
    networks:
      - microservices-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  pgdata:
  rabbitmq_data:
