
services:
  eureka-server:
    image: cleosilva/eureka-server:${BUILD_ID} # Ou use ${BUILD_NUMBER} se preferir
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  jenkins_data: