server:
  port: 8761 # Porta padrão do Eureka

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false # O próprio Eureka Server não se registra
    fetchRegistry: false # Não busca o registro de outros serviços
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/