server:
  port: 8200

spring:
  application:
    name: order-simulator

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        auto-startup: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/