server:
  port: 8100 # Uma porta dentro da faixa permitida

spring:
  application:
    name: product-catalog
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: rabbitmq #Nome do serviço RabbitMQ no docker-compose
    port: 5672
    username: guest
    password: guest
    listener: # Configurações para o consumidor (útil para ambos, mesmo que um seja só produtor no início)
      simple:
        auto-startup: true
        # acknowledge-mode: manual # Opcional: para controle manual do ack da mensagem

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/