server:
  port: 8100 # Uma porta dentro da faixa permitida

spring:
  application:
    name: product-catalog
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/